# UF Research Computing  

![UF Research Computing Logo](images/ufrc_logo.png)

## Training module on Pytorch for image classification


This training module is based off of the [Deep Learning with Pytorch: A 60 minute blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) tutorial by Soumith Chintala.

It has been updated and customized fro running on HiPerGator by Matt Gitzendanner.



## Part 1: What is PyTorch?


It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  A deep learning research platform that provides maximum flexibility
   and speed

## Getting Started


### Tensors

Tensors are similar to NumPy’s `ndarrays`, or more generally, a multidimensional matrix, with the additional benefit being that
Tensors can also be used on a GPU to accelerate computing.

Let's start by importing our needed modules: torch and numpy

In [2]:
# Do we need this?? #from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:



<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



In [8]:
# Uninitialized matrix
x = torch.empty(5, 3)
print(x)

tensor([[1.0256e-08, 2.5783e-09, 3.0784e+12],
        [6.9372e-07, 1.6902e-04, 2.6225e-09],
        [1.2398e+16, 3.1369e+27, 1.6880e+25],
        [2.5226e-18, 5.3693e-05, 5.4651e-05],
        [2.1029e+20, 1.0488e-08, 1.9989e+20]])


Construct a randomly initialized matrix:



In [9]:
# Randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.5177, 0.2104, 0.9759],
        [0.1042, 0.0430, 0.5432],
        [0.0398, 0.4286, 0.5386],
        [0.3898, 0.0866, 0.6811],
        [0.9950, 0.1854, 0.1376]])


Construct a matrix filled zeros and of dtype long (a 64-bit integer):



In [13]:
# Matrix filled with 0s, specifying long integer data type
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [15]:
# Matrix with specified values
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, and device (e.g. `device='cuda'`), unless
new values are provided by user



In [17]:
y = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(y)

y = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(y)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.3073,  1.7252,  0.9808],
        [ 0.4105,  0.2537, -0.2921],
        [-0.3623, -0.0601,  0.2346],
        [ 0.8938,  1.3957, -1.1560],
        [ 0.9353,  0.4291, -0.0738]])


Get its size:



In [18]:
print(y.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [20]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0721,  1.3995,  1.0863],
        [-2.3711,  0.7235,  0.6999],
        [-0.0660,  1.2769,  1.3639],
        [ 1.0590, -0.0471, -0.5368],
        [ 1.0610,  1.9492, -1.0509]])


Addition: syntax 2



In [21]:
print(torch.add(x, y))

tensor([[ 0.0721,  1.3995,  1.0863],
        [-2.3711,  0.7235,  0.6999],
        [-0.0660,  1.2769,  1.3639],
        [ 1.0590, -0.0471, -0.5368],
        [ 1.0610,  1.9492, -1.0509]])


Addition: providing an output tensor as argument



In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0721,  1.3995,  1.0863],
        [-2.3711,  0.7235,  0.6999],
        [-0.0660,  1.2769,  1.3639],
        [ 1.0590, -0.0471, -0.5368],
        [ 1.0610,  1.9492, -1.0509]])


Addition: in-place



In [23]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.0721,  1.3995,  1.0863],
        [-2.3711,  0.7235,  0.6999],
        [-0.0660,  1.2769,  1.3639],
        [ 1.0590, -0.0471, -0.5368],
        [ 1.0610,  1.9492, -1.0509]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!


In [33]:
print("x is: \n", x)
print("Cloumn 1 of x is:", x[:, 1]) # Rembember 0-indexing

x is: 
 tensor([[-0.0658,  0.5213,  0.7911],
        [-2.4323,  0.6531,  0.6004],
        [-1.0082,  0.9208,  0.4485],
        [ 0.9685, -0.7695, -0.9071],
        [ 0.7119,  1.9137, -1.4645]])
Cloumn 1 of x is: tensor([ 0.5213,  0.6531,  0.9208, -0.7695,  1.9137])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [39]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])
tensor([[ 1.6179,  0.2050,  0.1634, -1.6854],
        [ 0.3592, -0.9925,  1.1974, -0.5053],
        [ 0.3456, -0.5126, -0.3245, -1.0524],
        [ 0.8773, -0.9082, -0.2550, -1.0428]])
tensor([ 1.6179,  0.2050,  0.1634, -1.6854,  0.3592, -0.9925,  1.1974, -0.5053,
         0.3456, -0.5126, -0.3245, -1.0524,  0.8773, -0.9082, -0.2550, -1.0428])
tensor([[ 1.6179,  0.2050],
        [ 0.1634, -1.6854],
        [ 0.3592, -0.9925],
        [ 1.1974, -0.5053],
        [ 0.3456, -0.5126],
        [-0.3245, -1.0524],
        [ 0.8773, -0.9082],
        [-0.2550, -1.0428]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [40]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5930])
-1.5929841995239258


#### Read later


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described here: [https://pytorch.org/docs/torch](https://pytorch.org/docs/torch)


## NumPy Bridge


Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

### Converting a Torch Tensor to a NumPy Array




In [43]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [47]:
b = a.numpy()
print(b)

[2. 2. 2. 2. 2.]


See how the numpy array changed in value when the torch array is modified.

This is similar to python lists. If `list1 = [1,2,3]` and you do `list2=list1`, you are telling python that `list2` should point to the same place in memory as `list1`. Changing an element in either list changes the corresponding element in the other--they are just different names pointing to the same memory structure.



In [49]:
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [51]:
# Create a new np array
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [57]:
# The if statement checks to see if a GPU is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.rand(3,5, device=device)     # directly create a tensor on GPU
    x = torch.rand(3,5).to(device)         # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[0.4642, 1.0532, 1.0966, 1.7360, 0.0656],
        [1.0100, 1.1297, 1.0439, 0.7124, 1.6135],
        [1.7370, 1.0953, 1.4682, 0.8548, 0.5511]], device='cuda:0')
tensor([[0.4642, 1.0532, 1.0966, 1.7360, 0.0656],
        [1.0100, 1.1297, 1.0439, 0.7124, 1.6135],
        [1.7370, 1.0953, 1.4682, 0.8548, 0.5511]], dtype=torch.float64)


**[Continue to part 2 of the tutorial: 2_autograd_tutorial.ipynb](2_autograd_tutorial.ipynb)**